# Generated by Django 3.2.6 on 2021-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('userphoto', models.ImageField(upload_to='uploads/userprofile')),
                ('password', models.CharField(max_length=150)),
            ],
        ),
    ]
